// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtobufMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages
{

    /// <summary>Holder for reflection information generated from ProtobufMessages.proto</summary>
    public static partial class ProtobufMessagesReflection
    {

        #region Descriptor
        /// <summary>File descriptor for ProtobufMessages.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static ProtobufMessagesReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChZQcm90b2J1Zk1lc3NhZ2VzLnByb3RvEghtZXNzYWdlcyIKCghQaW5nUG9u",
                  "ZyKTAgoIUG9zaXRpb24SEgoKdHJhY2tlcl9pZBgBIAEoBRIOCgF4GAIgASgC",
                  "SACIAQESDgoBeRgDIAEoAkgBiAEBEg4KAXoYBCABKAJIAogBARIKCgJxeBgF",
                  "IAEoAhIKCgJxeRgGIAEoAhIKCgJxehgHIAEoAhIKCgJxdxgIIAEoAhI3Cgtk",
                  "YXRhX3NvdXJjZRgJIAEoDjIdLm1lc3NhZ2VzLlBvc2l0aW9uLkRhdGFTb3Vy",
                  "Y2VIA4gBASI4CgpEYXRhU291cmNlEggKBE5PTkUQABIHCgNJTVUQARINCglQ",
                  "UkVDSVNJT04QAhIICgRGVUxMEANCBAoCX3hCBAoCX3lCBAoCX3pCDgoMX2Rh",
                  "dGFfc291cmNlIpcBCgpVc2VyQWN0aW9uEgwKBG5hbWUYASABKAkSQwoQYWN0",
                  "aW9uX2FyZ3VtZW50cxgCIAMoCzIpLm1lc3NhZ2VzLlVzZXJBY3Rpb24uQWN0",
                  "aW9uQXJndW1lbnRzRW50cnkaNgoUQWN0aW9uQXJndW1lbnRzRW50cnkSCwoD",
                  "a2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJmCgxUcmFja2VyQWRkZWQS",
                  "EgoKdHJhY2tlcl9pZBgBIAEoBRIWCg50cmFja2VyX3NlcmlhbBgCIAEoCRIU",
                  "Cgx0cmFja2VyX25hbWUYAyABKAkSFAoMdHJhY2tlcl9yb2xlGAQgASgFIvwC",
                  "Cg1UcmFja2VyU3RhdHVzEhIKCnRyYWNrZXJfaWQYASABKAUSLgoGc3RhdHVz",
                  "GAIgASgOMh4ubWVzc2FnZXMuVHJhY2tlclN0YXR1cy5TdGF0dXMSMQoFZXh0",
                  "cmEYAyADKAsyIi5tZXNzYWdlcy5UcmFja2VyU3RhdHVzLkV4dHJhRW50cnkS",
                  "OwoKY29uZmlkZW5jZRgEIAEoDjIiLm1lc3NhZ2VzLlRyYWNrZXJTdGF0dXMu",
                  "Q29uZmlkZW5jZUgAiAEBGiwKCkV4dHJhRW50cnkSCwoDa2V5GAEgASgJEg0K",
                  "BXZhbHVlGAIgASgJOgI4ASJFCgZTdGF0dXMSEAoMRElTQ09OTkVDVEVEEAAS",
                  "BgoCT0sQARIICgRCVVNZEAISCQoFRVJST1IQAxIMCghPQ0NMVURFRBAEIjMK",
                  "CkNvbmZpZGVuY2USBgoCTk8QABIHCgNMT1cQARIKCgZNRURJVU0QBRIICgRI",
                  "SUdIEApCDQoLX2NvbmZpZGVuY2Ui1QEKD1Byb3RvYnVmTWVzc2FnZRImCghw",
                  "b3NpdGlvbhgBIAEoCzISLm1lc3NhZ2VzLlBvc2l0aW9uSAASKwoLdXNlcl9h",
                  "Y3Rpb24YAiABKAsyFC5tZXNzYWdlcy5Vc2VyQWN0aW9uSAASLwoNdHJhY2tl",
                  "cl9hZGRlZBgDIAEoCzIWLm1lc3NhZ2VzLlRyYWNrZXJBZGRlZEgAEjEKDnRy",
                  "YWNrZXJfc3RhdHVzGAQgASgLMhcubWVzc2FnZXMuVHJhY2tlclN0YXR1c0gA",
                  "QgkKB21lc3NhZ2VCJgoSZGV2LnNsaW1ldnIuYnJpZGdlQhBQcm90b2J1Zk1l",
                  "c3NhZ2VzYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.PingPong), global::Messages.PingPong.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Position), global::Messages.Position.Parser, new[]{ "TrackerId", "X", "Y", "Z", "Qx", "Qy", "Qz", "Qw", "DataSource" }, new[]{ "X", "Y", "Z", "DataSource" }, new[]{ typeof(global::Messages.Position.Types.DataSource) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.UserAction), global::Messages.UserAction.Parser, new[]{ "Name", "ActionArguments" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.TrackerAdded), global::Messages.TrackerAdded.Parser, new[]{ "TrackerId", "TrackerSerial", "TrackerName", "TrackerRole" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.TrackerStatus), global::Messages.TrackerStatus.Parser, new[]{ "TrackerId", "Status", "Extra", "Confidence" }, new[]{ "Confidence" }, new[]{ typeof(global::Messages.TrackerStatus.Types.Status), typeof(global::Messages.TrackerStatus.Types.Confidence) }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.ProtobufMessage), global::Messages.ProtobufMessage.Parser, new[]{ "Position", "UserAction", "TrackerAdded", "TrackerStatus" }, new[]{ "Message" }, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class PingPong : pb::IMessage<PingPong>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<PingPong> _parser = new pb::MessageParser<PingPong>(() => new PingPong());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PingPong> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PingPong()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PingPong(PingPong other) : this()
        {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PingPong Clone()
        {
            return new PingPong(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as PingPong);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PingPong other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PingPong other)
        {
            if (other == null)
            {
                return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                }
            }
        }
#endif

    }

    public sealed partial class Position : pb::IMessage<Position>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Position> _parser = new pb::MessageParser<Position>(() => new Position());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Position> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Position()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Position(Position other) : this()
        {
            _hasBits0 = other._hasBits0;
            trackerId_ = other.trackerId_;
            x_ = other.x_;
            y_ = other.y_;
            z_ = other.z_;
            qx_ = other.qx_;
            qy_ = other.qy_;
            qz_ = other.qz_;
            qw_ = other.qw_;
            dataSource_ = other.dataSource_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Position Clone()
        {
            return new Position(this);
        }

        /// <summary>Field number for the "tracker_id" field.</summary>
        public const int TrackerIdFieldNumber = 1;
        private int trackerId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TrackerId
        {
            get { return trackerId_; }
            set
            {
                trackerId_ = value;
            }
        }

        /// <summary>Field number for the "x" field.</summary>
        public const int XFieldNumber = 2;
        private readonly static float XDefaultValue = 0F;

        private float x_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float X
        {
            get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
            set
            {
                _hasBits0 |= 1;
                x_ = value;
            }
        }
        /// <summary>Gets whether the "x" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasX
        {
            get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "x" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearX()
        {
            _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "y" field.</summary>
        public const int YFieldNumber = 3;
        private readonly static float YDefaultValue = 0F;

        private float y_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Y
        {
            get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
            set
            {
                _hasBits0 |= 2;
                y_ = value;
            }
        }
        /// <summary>Gets whether the "y" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasY
        {
            get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "y" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearY()
        {
            _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "z" field.</summary>
        public const int ZFieldNumber = 4;
        private readonly static float ZDefaultValue = 0F;

        private float z_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Z
        {
            get { if ((_hasBits0 & 4) != 0) { return z_; } else { return ZDefaultValue; } }
            set
            {
                _hasBits0 |= 4;
                z_ = value;
            }
        }
        /// <summary>Gets whether the "z" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasZ
        {
            get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "z" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearZ()
        {
            _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "qx" field.</summary>
        public const int QxFieldNumber = 5;
        private float qx_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Qx
        {
            get { return qx_; }
            set
            {
                qx_ = value;
            }
        }

        /// <summary>Field number for the "qy" field.</summary>
        public const int QyFieldNumber = 6;
        private float qy_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Qy
        {
            get { return qy_; }
            set
            {
                qy_ = value;
            }
        }

        /// <summary>Field number for the "qz" field.</summary>
        public const int QzFieldNumber = 7;
        private float qz_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Qz
        {
            get { return qz_; }
            set
            {
                qz_ = value;
            }
        }

        /// <summary>Field number for the "qw" field.</summary>
        public const int QwFieldNumber = 8;
        private float qw_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Qw
        {
            get { return qw_; }
            set
            {
                qw_ = value;
            }
        }

        /// <summary>Field number for the "data_source" field.</summary>
        public const int DataSourceFieldNumber = 9;
        private readonly static global::Messages.Position.Types.DataSource DataSourceDefaultValue = global::Messages.Position.Types.DataSource.None;

        private global::Messages.Position.Types.DataSource dataSource_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.Position.Types.DataSource DataSource
        {
            get { if ((_hasBits0 & 8) != 0) { return dataSource_; } else { return DataSourceDefaultValue; } }
            set
            {
                _hasBits0 |= 8;
                dataSource_ = value;
            }
        }
        /// <summary>Gets whether the "data_source" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDataSource
        {
            get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "data_source" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDataSource()
        {
            _hasBits0 &= ~8;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Position);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Position other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (TrackerId != other.TrackerId) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qx, other.Qx)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qy, other.Qy)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qz, other.Qz)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Qw, other.Qw)) return false;
            if (DataSource != other.DataSource) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (TrackerId != 0) hash ^= TrackerId.GetHashCode();
            if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
            if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
            if (HasZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
            if (Qx != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qx);
            if (Qy != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qy);
            if (Qz != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qz);
            if (Qw != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Qw);
            if (HasDataSource) hash ^= DataSource.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (TrackerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TrackerId);
      }
      if (HasX) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (HasY) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (HasZ) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Qx != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Qx);
      }
      if (Qy != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Qy);
      }
      if (Qz != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Qz);
      }
      if (Qw != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Qw);
      }
      if (HasDataSource) {
        output.WriteRawTag(72);
        output.WriteEnum((int) DataSource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (TrackerId != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(TrackerId);
            }
            if (HasX)
            {
                output.WriteRawTag(21);
                output.WriteFloat(X);
            }
            if (HasY)
            {
                output.WriteRawTag(29);
                output.WriteFloat(Y);
            }
            if (HasZ)
            {
                output.WriteRawTag(37);
                output.WriteFloat(Z);
            }
            if (Qx != 0F)
            {
                output.WriteRawTag(45);
                output.WriteFloat(Qx);
            }
            if (Qy != 0F)
            {
                output.WriteRawTag(53);
                output.WriteFloat(Qy);
            }
            if (Qz != 0F)
            {
                output.WriteRawTag(61);
                output.WriteFloat(Qz);
            }
            if (Qw != 0F)
            {
                output.WriteRawTag(69);
                output.WriteFloat(Qw);
            }
            if (HasDataSource)
            {
                output.WriteRawTag(72);
                output.WriteEnum((int)DataSource);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (TrackerId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrackerId);
            }
            if (HasX)
            {
                size += 1 + 4;
            }
            if (HasY)
            {
                size += 1 + 4;
            }
            if (HasZ)
            {
                size += 1 + 4;
            }
            if (Qx != 0F)
            {
                size += 1 + 4;
            }
            if (Qy != 0F)
            {
                size += 1 + 4;
            }
            if (Qz != 0F)
            {
                size += 1 + 4;
            }
            if (Qw != 0F)
            {
                size += 1 + 4;
            }
            if (HasDataSource)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)DataSource);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Position other)
        {
            if (other == null)
            {
                return;
            }
            if (other.TrackerId != 0)
            {
                TrackerId = other.TrackerId;
            }
            if (other.HasX)
            {
                X = other.X;
            }
            if (other.HasY)
            {
                Y = other.Y;
            }
            if (other.HasZ)
            {
                Z = other.Z;
            }
            if (other.Qx != 0F)
            {
                Qx = other.Qx;
            }
            if (other.Qy != 0F)
            {
                Qy = other.Qy;
            }
            if (other.Qz != 0F)
            {
                Qz = other.Qz;
            }
            if (other.Qw != 0F)
            {
                Qw = other.Qw;
            }
            if (other.HasDataSource)
            {
                DataSource = other.DataSource;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TrackerId = input.ReadInt32();
            break;
          }
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 45: {
            Qx = input.ReadFloat();
            break;
          }
          case 53: {
            Qy = input.ReadFloat();
            break;
          }
          case 61: {
            Qz = input.ReadFloat();
            break;
          }
          case 69: {
            Qw = input.ReadFloat();
            break;
          }
          case 72: {
            DataSource = (global::Messages.Position.Types.DataSource) input.ReadEnum();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            TrackerId = input.ReadInt32();
                            break;
                        }
                    case 21:
                        {
                            X = input.ReadFloat();
                            break;
                        }
                    case 29:
                        {
                            Y = input.ReadFloat();
                            break;
                        }
                    case 37:
                        {
                            Z = input.ReadFloat();
                            break;
                        }
                    case 45:
                        {
                            Qx = input.ReadFloat();
                            break;
                        }
                    case 53:
                        {
                            Qy = input.ReadFloat();
                            break;
                        }
                    case 61:
                        {
                            Qz = input.ReadFloat();
                            break;
                        }
                    case 69:
                        {
                            Qw = input.ReadFloat();
                            break;
                        }
                    case 72:
                        {
                            DataSource = (global::Messages.Position.Types.DataSource)input.ReadEnum();
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the Position message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum DataSource
            {
                [pbr::OriginalName("NONE")] None = 0,
                [pbr::OriginalName("IMU")] Imu = 1,
                [pbr::OriginalName("PRECISION")] Precision = 2,
                [pbr::OriginalName("FULL")] Full = 3,
            }

        }
        #endregion

    }

    public sealed partial class UserAction : pb::IMessage<UserAction>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<UserAction> _parser = new pb::MessageParser<UserAction>(() => new UserAction());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<UserAction> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserAction()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserAction(UserAction other) : this()
        {
            name_ = other.name_;
            actionArguments_ = other.actionArguments_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserAction Clone()
        {
            return new UserAction(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name
        {
            get { return name_; }
            set
            {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "action_arguments" field.</summary>
        public const int ActionArgumentsFieldNumber = 2;
        private static readonly pbc::MapField<string, string>.Codec _map_actionArguments_codec
            = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 18);
        private readonly pbc::MapField<string, string> actionArguments_ = new pbc::MapField<string, string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<string, string> ActionArguments
        {
            get { return actionArguments_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as UserAction);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(UserAction other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Name != other.Name) return false;
            if (!ActionArguments.Equals(other.ActionArguments)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Name.Length != 0) hash ^= Name.GetHashCode();
            hash ^= ActionArguments.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      actionArguments_.WriteTo(output, _map_actionArguments_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Name.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Name);
            }
            actionArguments_.WriteTo(ref output, _map_actionArguments_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Name.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
            }
            size += actionArguments_.CalculateSize(_map_actionArguments_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(UserAction other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Name.Length != 0)
            {
                Name = other.Name;
            }
            actionArguments_.MergeFrom(other.actionArguments_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            actionArguments_.AddEntriesFrom(input, _map_actionArguments_codec);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Name = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            actionArguments_.AddEntriesFrom(ref input, _map_actionArguments_codec);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class TrackerAdded : pb::IMessage<TrackerAdded>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<TrackerAdded> _parser = new pb::MessageParser<TrackerAdded>(() => new TrackerAdded());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TrackerAdded> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerAdded()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerAdded(TrackerAdded other) : this()
        {
            trackerId_ = other.trackerId_;
            trackerSerial_ = other.trackerSerial_;
            trackerName_ = other.trackerName_;
            trackerRole_ = other.trackerRole_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerAdded Clone()
        {
            return new TrackerAdded(this);
        }

        /// <summary>Field number for the "tracker_id" field.</summary>
        public const int TrackerIdFieldNumber = 1;
        private int trackerId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TrackerId
        {
            get { return trackerId_; }
            set
            {
                trackerId_ = value;
            }
        }

        /// <summary>Field number for the "tracker_serial" field.</summary>
        public const int TrackerSerialFieldNumber = 2;
        private string trackerSerial_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TrackerSerial
        {
            get { return trackerSerial_; }
            set
            {
                trackerSerial_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "tracker_name" field.</summary>
        public const int TrackerNameFieldNumber = 3;
        private string trackerName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TrackerName
        {
            get { return trackerName_; }
            set
            {
                trackerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "tracker_role" field.</summary>
        public const int TrackerRoleFieldNumber = 4;
        private int trackerRole_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TrackerRole
        {
            get { return trackerRole_; }
            set
            {
                trackerRole_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as TrackerAdded);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TrackerAdded other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (TrackerId != other.TrackerId) return false;
            if (TrackerSerial != other.TrackerSerial) return false;
            if (TrackerName != other.TrackerName) return false;
            if (TrackerRole != other.TrackerRole) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (TrackerId != 0) hash ^= TrackerId.GetHashCode();
            if (TrackerSerial.Length != 0) hash ^= TrackerSerial.GetHashCode();
            if (TrackerName.Length != 0) hash ^= TrackerName.GetHashCode();
            if (TrackerRole != 0) hash ^= TrackerRole.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (TrackerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TrackerId);
      }
      if (TrackerSerial.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TrackerSerial);
      }
      if (TrackerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TrackerName);
      }
      if (TrackerRole != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TrackerRole);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (TrackerId != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(TrackerId);
            }
            if (TrackerSerial.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(TrackerSerial);
            }
            if (TrackerName.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(TrackerName);
            }
            if (TrackerRole != 0)
            {
                output.WriteRawTag(32);
                output.WriteInt32(TrackerRole);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (TrackerId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrackerId);
            }
            if (TrackerSerial.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(TrackerSerial);
            }
            if (TrackerName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(TrackerName);
            }
            if (TrackerRole != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrackerRole);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TrackerAdded other)
        {
            if (other == null)
            {
                return;
            }
            if (other.TrackerId != 0)
            {
                TrackerId = other.TrackerId;
            }
            if (other.TrackerSerial.Length != 0)
            {
                TrackerSerial = other.TrackerSerial;
            }
            if (other.TrackerName.Length != 0)
            {
                TrackerName = other.TrackerName;
            }
            if (other.TrackerRole != 0)
            {
                TrackerRole = other.TrackerRole;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TrackerId = input.ReadInt32();
            break;
          }
          case 18: {
            TrackerSerial = input.ReadString();
            break;
          }
          case 26: {
            TrackerName = input.ReadString();
            break;
          }
          case 32: {
            TrackerRole = input.ReadInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            TrackerId = input.ReadInt32();
                            break;
                        }
                    case 18:
                        {
                            TrackerSerial = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            TrackerName = input.ReadString();
                            break;
                        }
                    case 32:
                        {
                            TrackerRole = input.ReadInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class TrackerStatus : pb::IMessage<TrackerStatus>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<TrackerStatus> _parser = new pb::MessageParser<TrackerStatus>(() => new TrackerStatus());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TrackerStatus> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerStatus()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerStatus(TrackerStatus other) : this()
        {
            _hasBits0 = other._hasBits0;
            trackerId_ = other.trackerId_;
            status_ = other.status_;
            extra_ = other.extra_.Clone();
            confidence_ = other.confidence_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackerStatus Clone()
        {
            return new TrackerStatus(this);
        }

        /// <summary>Field number for the "tracker_id" field.</summary>
        public const int TrackerIdFieldNumber = 1;
        private int trackerId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TrackerId
        {
            get { return trackerId_; }
            set
            {
                trackerId_ = value;
            }
        }

        /// <summary>Field number for the "status" field.</summary>
        public const int StatusFieldNumber = 2;
        private global::Messages.TrackerStatus.Types.Status status_ = global::Messages.TrackerStatus.Types.Status.Disconnected;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.TrackerStatus.Types.Status Status
        {
            get { return status_; }
            set
            {
                status_ = value;
            }
        }

        /// <summary>Field number for the "extra" field.</summary>
        public const int ExtraFieldNumber = 3;
        private static readonly pbc::MapField<string, string>.Codec _map_extra_codec
            = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 26);
        private readonly pbc::MapField<string, string> extra_ = new pbc::MapField<string, string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<string, string> Extra
        {
            get { return extra_; }
        }

        /// <summary>Field number for the "confidence" field.</summary>
        public const int ConfidenceFieldNumber = 4;
        private readonly static global::Messages.TrackerStatus.Types.Confidence ConfidenceDefaultValue = global::Messages.TrackerStatus.Types.Confidence.No;

        private global::Messages.TrackerStatus.Types.Confidence confidence_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.TrackerStatus.Types.Confidence Confidence
        {
            get { if ((_hasBits0 & 1) != 0) { return confidence_; } else { return ConfidenceDefaultValue; } }
            set
            {
                _hasBits0 |= 1;
                confidence_ = value;
            }
        }
        /// <summary>Gets whether the "confidence" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasConfidence
        {
            get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "confidence" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearConfidence()
        {
            _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as TrackerStatus);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TrackerStatus other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (TrackerId != other.TrackerId) return false;
            if (Status != other.Status) return false;
            if (!Extra.Equals(other.Extra)) return false;
            if (Confidence != other.Confidence) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (TrackerId != 0) hash ^= TrackerId.GetHashCode();
            if (Status != global::Messages.TrackerStatus.Types.Status.Disconnected) hash ^= Status.GetHashCode();
            hash ^= Extra.GetHashCode();
            if (HasConfidence) hash ^= Confidence.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (TrackerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TrackerId);
      }
      if (Status != global::Messages.TrackerStatus.Types.Status.Disconnected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      extra_.WriteTo(output, _map_extra_codec);
      if (HasConfidence) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (TrackerId != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(TrackerId);
            }
            if (Status != global::Messages.TrackerStatus.Types.Status.Disconnected)
            {
                output.WriteRawTag(16);
                output.WriteEnum((int)Status);
            }
            extra_.WriteTo(ref output, _map_extra_codec);
            if (HasConfidence)
            {
                output.WriteRawTag(32);
                output.WriteEnum((int)Confidence);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (TrackerId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrackerId);
            }
            if (Status != global::Messages.TrackerStatus.Types.Status.Disconnected)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Status);
            }
            size += extra_.CalculateSize(_map_extra_codec);
            if (HasConfidence)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Confidence);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TrackerStatus other)
        {
            if (other == null)
            {
                return;
            }
            if (other.TrackerId != 0)
            {
                TrackerId = other.TrackerId;
            }
            if (other.Status != global::Messages.TrackerStatus.Types.Status.Disconnected)
            {
                Status = other.Status;
            }
            extra_.MergeFrom(other.extra_);
            if (other.HasConfidence)
            {
                Confidence = other.Confidence;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TrackerId = input.ReadInt32();
            break;
          }
          case 16: {
            Status = (global::Messages.TrackerStatus.Types.Status) input.ReadEnum();
            break;
          }
          case 26: {
            extra_.AddEntriesFrom(input, _map_extra_codec);
            break;
          }
          case 32: {
            Confidence = (global::Messages.TrackerStatus.Types.Confidence) input.ReadEnum();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            TrackerId = input.ReadInt32();
                            break;
                        }
                    case 16:
                        {
                            Status = (global::Messages.TrackerStatus.Types.Status)input.ReadEnum();
                            break;
                        }
                    case 26:
                        {
                            extra_.AddEntriesFrom(ref input, _map_extra_codec);
                            break;
                        }
                    case 32:
                        {
                            Confidence = (global::Messages.TrackerStatus.Types.Confidence)input.ReadEnum();
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the TrackerStatus message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum Status
            {
                [pbr::OriginalName("DISCONNECTED")] Disconnected = 0,
                [pbr::OriginalName("OK")] Ok = 1,
                [pbr::OriginalName("BUSY")] Busy = 2,
                [pbr::OriginalName("ERROR")] Error = 3,
                [pbr::OriginalName("OCCLUDED")] Occluded = 4,
            }

            public enum Confidence
            {
                [pbr::OriginalName("NO")] No = 0,
                [pbr::OriginalName("LOW")] Low = 1,
                [pbr::OriginalName("MEDIUM")] Medium = 5,
                [pbr::OriginalName("HIGH")] High = 10,
            }

        }
        #endregion

    }

    public sealed partial class ProtobufMessage : pb::IMessage<ProtobufMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<ProtobufMessage> _parser = new pb::MessageParser<ProtobufMessage>(() => new ProtobufMessage());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ProtobufMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Messages.ProtobufMessagesReflection.Descriptor.MessageTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ProtobufMessage()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ProtobufMessage(ProtobufMessage other) : this()
        {
            switch (other.MessageCase)
            {
                case MessageOneofCase.Position:
                    Position = other.Position.Clone();
                    break;
                case MessageOneofCase.UserAction:
                    UserAction = other.UserAction.Clone();
                    break;
                case MessageOneofCase.TrackerAdded:
                    TrackerAdded = other.TrackerAdded.Clone();
                    break;
                case MessageOneofCase.TrackerStatus:
                    TrackerStatus = other.TrackerStatus.Clone();
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ProtobufMessage Clone()
        {
            return new ProtobufMessage(this);
        }

        /// <summary>Field number for the "position" field.</summary>
        public const int PositionFieldNumber = 1;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.Position Position
        {
            get { return messageCase_ == MessageOneofCase.Position ? (global::Messages.Position)message_ : null; }
            set
            {
                message_ = value;
                messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Position;
            }
        }

        /// <summary>Field number for the "user_action" field.</summary>
        public const int UserActionFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.UserAction UserAction
        {
            get { return messageCase_ == MessageOneofCase.UserAction ? (global::Messages.UserAction)message_ : null; }
            set
            {
                message_ = value;
                messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.UserAction;
            }
        }

        /// <summary>Field number for the "tracker_added" field.</summary>
        public const int TrackerAddedFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.TrackerAdded TrackerAdded
        {
            get { return messageCase_ == MessageOneofCase.TrackerAdded ? (global::Messages.TrackerAdded)message_ : null; }
            set
            {
                message_ = value;
                messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.TrackerAdded;
            }
        }

        /// <summary>Field number for the "tracker_status" field.</summary>
        public const int TrackerStatusFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Messages.TrackerStatus TrackerStatus
        {
            get { return messageCase_ == MessageOneofCase.TrackerStatus ? (global::Messages.TrackerStatus)message_ : null; }
            set
            {
                message_ = value;
                messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.TrackerStatus;
            }
        }

        private object message_;
        /// <summary>Enum of possible cases for the "message" oneof.</summary>
        public enum MessageOneofCase
        {
            None = 0,
            Position = 1,
            UserAction = 2,
            TrackerAdded = 3,
            TrackerStatus = 4,
        }
        private MessageOneofCase messageCase_ = MessageOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MessageOneofCase MessageCase
        {
            get { return messageCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearMessage()
        {
            messageCase_ = MessageOneofCase.None;
            message_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as ProtobufMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ProtobufMessage other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(Position, other.Position)) return false;
            if (!object.Equals(UserAction, other.UserAction)) return false;
            if (!object.Equals(TrackerAdded, other.TrackerAdded)) return false;
            if (!object.Equals(TrackerStatus, other.TrackerStatus)) return false;
            if (MessageCase != other.MessageCase) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (messageCase_ == MessageOneofCase.Position) hash ^= Position.GetHashCode();
            if (messageCase_ == MessageOneofCase.UserAction) hash ^= UserAction.GetHashCode();
            if (messageCase_ == MessageOneofCase.TrackerAdded) hash ^= TrackerAdded.GetHashCode();
            if (messageCase_ == MessageOneofCase.TrackerStatus) hash ^= TrackerStatus.GetHashCode();
            hash ^= (int)messageCase_;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (messageCase_ == MessageOneofCase.Position) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      if (messageCase_ == MessageOneofCase.UserAction) {
        output.WriteRawTag(18);
        output.WriteMessage(UserAction);
      }
      if (messageCase_ == MessageOneofCase.TrackerAdded) {
        output.WriteRawTag(26);
        output.WriteMessage(TrackerAdded);
      }
      if (messageCase_ == MessageOneofCase.TrackerStatus) {
        output.WriteRawTag(34);
        output.WriteMessage(TrackerStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (messageCase_ == MessageOneofCase.Position)
            {
                output.WriteRawTag(10);
                output.WriteMessage(Position);
            }
            if (messageCase_ == MessageOneofCase.UserAction)
            {
                output.WriteRawTag(18);
                output.WriteMessage(UserAction);
            }
            if (messageCase_ == MessageOneofCase.TrackerAdded)
            {
                output.WriteRawTag(26);
                output.WriteMessage(TrackerAdded);
            }
            if (messageCase_ == MessageOneofCase.TrackerStatus)
            {
                output.WriteRawTag(34);
                output.WriteMessage(TrackerStatus);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (messageCase_ == MessageOneofCase.Position)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
            }
            if (messageCase_ == MessageOneofCase.UserAction)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserAction);
            }
            if (messageCase_ == MessageOneofCase.TrackerAdded)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrackerAdded);
            }
            if (messageCase_ == MessageOneofCase.TrackerStatus)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrackerStatus);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ProtobufMessage other)
        {
            if (other == null)
            {
                return;
            }
            switch (other.MessageCase)
            {
                case MessageOneofCase.Position:
                    if (Position == null)
                    {
                        Position = new global::Messages.Position();
                    }
                    Position.MergeFrom(other.Position);
                    break;
                case MessageOneofCase.UserAction:
                    if (UserAction == null)
                    {
                        UserAction = new global::Messages.UserAction();
                    }
                    UserAction.MergeFrom(other.UserAction);
                    break;
                case MessageOneofCase.TrackerAdded:
                    if (TrackerAdded == null)
                    {
                        TrackerAdded = new global::Messages.TrackerAdded();
                    }
                    TrackerAdded.MergeFrom(other.TrackerAdded);
                    break;
                case MessageOneofCase.TrackerStatus:
                    if (TrackerStatus == null)
                    {
                        TrackerStatus = new global::Messages.TrackerStatus();
                    }
                    TrackerStatus.MergeFrom(other.TrackerStatus);
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Messages.Position subBuilder = new global::Messages.Position();
            if (messageCase_ == MessageOneofCase.Position) {
              subBuilder.MergeFrom(Position);
            }
            input.ReadMessage(subBuilder);
            Position = subBuilder;
            break;
          }
          case 18: {
            global::Messages.UserAction subBuilder = new global::Messages.UserAction();
            if (messageCase_ == MessageOneofCase.UserAction) {
              subBuilder.MergeFrom(UserAction);
            }
            input.ReadMessage(subBuilder);
            UserAction = subBuilder;
            break;
          }
          case 26: {
            global::Messages.TrackerAdded subBuilder = new global::Messages.TrackerAdded();
            if (messageCase_ == MessageOneofCase.TrackerAdded) {
              subBuilder.MergeFrom(TrackerAdded);
            }
            input.ReadMessage(subBuilder);
            TrackerAdded = subBuilder;
            break;
          }
          case 34: {
            global::Messages.TrackerStatus subBuilder = new global::Messages.TrackerStatus();
            if (messageCase_ == MessageOneofCase.TrackerStatus) {
              subBuilder.MergeFrom(TrackerStatus);
            }
            input.ReadMessage(subBuilder);
            TrackerStatus = subBuilder;
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            global::Messages.Position subBuilder = new global::Messages.Position();
                            if (messageCase_ == MessageOneofCase.Position)
                            {
                                subBuilder.MergeFrom(Position);
                            }
                            input.ReadMessage(subBuilder);
                            Position = subBuilder;
                            break;
                        }
                    case 18:
                        {
                            global::Messages.UserAction subBuilder = new global::Messages.UserAction();
                            if (messageCase_ == MessageOneofCase.UserAction)
                            {
                                subBuilder.MergeFrom(UserAction);
                            }
                            input.ReadMessage(subBuilder);
                            UserAction = subBuilder;
                            break;
                        }
                    case 26:
                        {
                            global::Messages.TrackerAdded subBuilder = new global::Messages.TrackerAdded();
                            if (messageCase_ == MessageOneofCase.TrackerAdded)
                            {
                                subBuilder.MergeFrom(TrackerAdded);
                            }
                            input.ReadMessage(subBuilder);
                            TrackerAdded = subBuilder;
                            break;
                        }
                    case 34:
                        {
                            global::Messages.TrackerStatus subBuilder = new global::Messages.TrackerStatus();
                            if (messageCase_ == MessageOneofCase.TrackerStatus)
                            {
                                subBuilder.MergeFrom(TrackerStatus);
                            }
                            input.ReadMessage(subBuilder);
                            TrackerStatus = subBuilder;
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
